### PR TITLE
GHC 8 support

### PR DESCRIPTION
**Pull request by LukaHorvat**
I've bumped version numbers and fixed some errors. This isn't yet finished because the `mysql` package needs to get fixed first. I'll update the pull request when that's taken care of (I've opened a pull request there as well).

### CODE REVIEW

**Comment by lykahb** [comment]
Thank you @LukaHorvat. This is a good start for GHC 8 support.
Many users still have older GHC so in the near future the updates still need to be backwards compatible with GHC 7.6+. Can you add the pragma around UndecidableSuperClasses to make the tests pass?

**Comment by LukaHorvat** [comment]
Yeah, no problem. I'll do that.

**Comment by lykahb** [comment]
@LukaHorvat Can you rebase into fewer commits? I'd like to merge this work in progress. If this is not enough to run Groundhog with GHC 8, the PR can be updated or you can open a new one.

Bumped transformers version
Enabled the UndecidableSuperClasses extension
Added PersistField context to instances as per the migration guide

**Comment by LukaHorvat** [comment]
I'm not that great at git manipulations. Can you suggest a simple way to do that? If not I could just open a new pull request with only those 3 commits and the pragma one manually added on top of them.

**Comment by LukaHorvat** [comment]
Check if this works for you.

**Comment by lykahb** [comment]
Merged, thanks!

**Pull request merged**
