### PR TITLE
Improved basic example

### PR DESCRIPTION
**Pull request by BartMassey**
Thanks much for `groundhog`. It is quite nice.

I found the basic example a bit hard to use and follow. Also, none of the examples answered my question about how to work with `MySQL` instead of in-memory `SQLite`.

Thus, I cleaned up and commented the basic example. I also added support for multiple databases (in-memory SQLite3, persistent SQLite3, MySQL, PostgresQL). I added a README describing operation.

### CODE REVIEW

**Comment by lykahb** [comment]
Thank you, the examples for connection and comments in db logics make a lot of sense. However, I am afraid that although basic.hs became more informative, it became also more complex. I think that it would be best to keep the first example no be bigger than the average screen height.

We can move the connection examples to haddock docs of withMySQLConn and withPostgresqlConn. As for giving runnable examples of other databases, we can rename dbSpecific to postgresCustomType.hs and switch another example to MySQL adding it to the filename for ease of search.

**Comment by BartMassey** [comment]
OK, how about this? The basic example gets even more basic, while remaining commented and readable. The fancier two-table example moves to `tables.hs`. The database selection stuff moves to `multidb.hs`. This seems to me to be easier for people diving into the example directory to follow.

Someone should probably build a README.md for this directory giving one-line explanations of the example files in the order they should be tried. It might not also hurt to put all of them in the cabal file. But I think there's no urgency here.

**Comment by lykahb** [comment]
Yes, README.md and comments for basic.hs will be a great improvement. Basic introduces mapping that has a single simple relation based on an autoincremented key. I think that we can keep it as-is only adding the comments. There are other examples which have two tables or more like keys.hs so tables.hs would be redundant. To me database selection looks more like a part of a potentially useful package or module than an example. Calling with*Conn with static values would look more straightforward. I agree about cabal. Perhaps this package should also be included into the travis file someday.

**Comment by BartMassey** [comment]
I've run out of time to work on this. Please go ahead and fix/rearrange things as you like and merge what you want. Perhaps I'll get a chance to look at it again in the future.

**Pull request closed without merging**
