### PR TITLE
Add check that certain Language Extensions are enabled

### PR DESCRIPTION
**Pull request by fendor**
For a source file:
```haskell
{-# LANGUAGE GADTs, TypeFamilies, TemplateHaskell, QuasiQuotes, StandaloneDeriving #-}
module Test where

import Control.Monad.IO.Class (liftIO)
import Database.Groundhog.TH
import Database.Groundhog.Postgresql

data Machine = Machine { modelName :: String, cost :: Double } deriving Show
data Part = Part { partName :: String, weight :: Int, machine :: DefaultKey Machine }
deriving instance Show Part

mkPersist defaultCodegenConfig [groundhog|
- entity: Machine
- entity: Part
|]

main :: IO ()
main = withPostgresqlConn "" $ runDbConn $ do
  runMigration $ do
    migrate (undefined :: Machine)
    migrate (undefined :: Part)
```
Note the missing `FlexibleInstances` Language Extension.
Turns the error message from this:
```
src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Read (Key Part BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for ‘Read (Key Part BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for ‘Show (Key Part a)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for ‘Show (Key Part a_aP3N)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for ‘Eq (Key Part a)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for ‘Eq (Key Part a_aP3N)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.SinglePersistField
           (Key Part BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.SinglePersistField (Key Part BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.PurePersistField
           (Key Part BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.PurePersistField (Key Part BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.PrimitivePersistField
           (Key Part BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.PrimitivePersistField (Key Part BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.PersistField (Key Part BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.PersistField (Key Part BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Read (Key Machine BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Read (Key Machine BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for ‘Show (Key Machine a)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for ‘Show (Key Machine a_aP2I)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for ‘Eq (Key Machine a)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for ‘Eq (Key Machine a_aP2I)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.SinglePersistField
           (Key Machine BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.SinglePersistField (Key Machine BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.PurePersistField
           (Key Machine BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.PurePersistField (Key Machine BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.PrimitivePersistField
           (Key Machine BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.PrimitivePersistField (Key Machine BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Test.hs:12:1: error:
    • Illegal instance declaration for
        ‘Database.Groundhog.Core.PersistField
           (Key Machine BackendSpecific)’
        (All instance types must be of the form (T a1 ... an)
         where a1 ... an are *distinct type variables*,
         and each type variable appears at most once in the instance head.
         Use FlexibleInstances if you want to disable this.)
    • In the instance declaration for
        ‘Database.Groundhog.Core.PersistField (Key Machine BackendSpecific)’
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
Into this:
```
src/Test.hs:12:1: error:
    Groundhog requires that you enable additionally the following language extensions: FlexibleInstances
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

While the error was arguably my fault for not copying exactly the example, I think this could make it easier for beginners if they forget language extensions since the error messages are kind of frightening. Even though the error message  told me what to do, it took me a long time to figure out the problem.

### CODE REVIEW

**Comment by fendor** [comment]
Thank you, done! Even improves the error message.

**Comment by fendor** [comment]
From a aesthetic point of view, turning the message into this:
```
src/Test.hs:12:1: error:
    Groundhog requires that you enable additionally the following language extensions:
         FlexibleInstances
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
Or maybe:
Groundhog requires that you enable additionally the following language extensions:
        - FlexibleInstances
        - ...
   |
12 | mkPersist defaultCodegenConfig [groundhog|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Do you think that would be better?

**Comment by lykahb** [comment]
The first one lets the user copy the missing extensions into the pragma without editing. Looks good to me.

**Comment by lykahb** [comment]
@fendor These changes broke the build https://travis-ci.org/lykahb/groundhog
Could you submit another PR to fix that? Thank you!

**Comment by fendor** [comment]
@lykahb I see, will fix immediately

**Pull request merged**
